### ISSUE TITLE
ramalama list crashes with AttributeError: 'str' object has no attribute 'timestamp'

### ISSUE THREAD

**Issue by amkr6207** [containers/ramalama#2586]
### Issue Description

Fresh install of `ramalama==0.18.0` in a new Python 3.12 virtual environment crashes on `ramalama list`.

The traceback points to `ramalama/model_store/global_store.py`, where `modified.timestamp()` is called, but `modified` is a string.

This reproduces consistently in a clean environment (new directory + new venv + fresh pip install), so it does not appear to be caused by local repo modifications.

### Steps to reproduce the issue

1. Create and activate a fresh virtual environment:
   ```bash
   python3 -m venv ramalama-testing
   source ramalama-testing/bin/activate

2. Install Ramalam:
 ```bash
pip install ramalama
```

3. Check Version
 ```bash
ramalama version
```

4. Run:
```bash
ramalama list
```

### Describe the results you received

**ramalama list crashes with**:

```
Traceback (most recent call last):
  File "/home/aman/OpenSource/outreachy/testing/ramalama-testing/bin/ramalama", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aman/OpenSource/outreachy/testing/ramalama-testing/lib/python3.12/site-packages/ramalama/cli.py", line 1235, in main
    args.func(args)
  File "/home/aman/OpenSource/outreachy/testing/ramalama-testing/lib/python3.12/site-packages/ramalama/cli.py", line 665, in list_cli
    models = _list_models(args)
             ^^^^^^^^^^^^^^^^^^
  File "/home/aman/OpenSource/outreachy/testing/ramalama-testing/lib/python3.12/site-packages/ramalama/cli.py", line 621, in _list_models
    return _list_models_from_store(args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aman/OpenSource/outreachy/testing/ramalama-testing/lib/python3.12/site-packages/ramalama/cli.py", line 588, in _list_models_from_store
    models = GlobalModelStore(args.store).list_models(engine=args.engine, show_container=args.container)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aman/OpenSource/outreachy/testing/ramalama-testing/lib/python3.12/site-packages/ramalama/model_store/global_store.py", line 82, in list_models
    modified_unix = modified.timestamp() if modified is not None else 0
                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'timestamp'
```

### Describe the results you expected

ramalama list should display the model list successfully, or gracefully handle non-datetime modified values without crashing.

### ramalama info output

```yaml
{
    "Accelerator": "none",
    "Config": {
        "benchmarks": {},
        "provider": {
            "openai": {}
        },
        "settings": {
            "config_files": [
                "/home/aman/OpenSource/outreachy/testing/ramalama-testing/share/ramalama/ramalama.conf"
            ]
        },
        "user": {}
    },
    "Engine": {
        "Info": {
            "host": {
                "arch": "amd64",
                "buildahVersion": "1.33.7",
                "cgroupControllers": [
                    "memory",
                    "pids"
                ],
                "cgroupManager": "systemd",
                "cgroupVersion": "v2",
                "conmon": {
                    "package": "Unknown",
                    "path": "/usr/bin/conmon",
                    "version": "conmon version 2.1.10, commit: unknown"
                },
                "cpuUtilization": {
                    "idlePercent": 91.74,
                    "systemPercent": 2.15,
                    "userPercent": 6.1
                },
                "cpus": 8,
                "databaseBackend": "sqlite",
                "distribution": {
                    "codename": "zena",
                    "distribution": "linuxmint",
                    "version": "22.3"
                },
                "eventLogger": "journald",
                "freeLocks": 2044,
                "hostname": "aman",
                "idMappings": {
                    "gidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1000,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 100000,
                            "size": 65536
                        }
                    ],
                    "uidmap": [
                        {
                            "container_id": 0,
                            "host_id": 1000,
                            "size": 1
                        },
                        {
                            "container_id": 1,
                            "host_id": 100000,
                            "size": 65536
                        }
                    ]
                },
                "kernel": "6.17.0-20-generic",
                "linkmode": "dynamic",
                "logDriver": "journald",
                "memFree": 635342848,
                "memTotal": 8203362304,
                "networkBackend": "netavark",
                "networkBackendInfo": {
                    "backend": "netavark",
                    "dns": {
                        "package": "Unknown",
                        "path": "/usr/lib/podman/aardvark-dns",
                        "version": "aardvark-dns 1.4.0"
                    },
                    "package": "Unknown",
                    "path": "/usr/lib/podman/netavark",
                    "version": "netavark 1.4.0"
                },
                "ociRuntime": {
                    "name": "crun",
                    "package": "Unknown",
                    "path": "/usr/bin/crun",
                    "version": "crun version 1.14.1\ncommit: de537a7965bfbe9992e2cfae0baeb56a08128171\nrundir: /run/user/1000/crun\nspec: 1.0.0\n+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +WASM:wasmedge +YAJL"
                },
                "os": "linux",
                "pasta": {
                    "executable": "/usr/bin/pasta",
                    "package": "Unknown",
                    "version": "pasta unknown version\nCopyright Red Hat\nGNU General Public License, version 2 or later\n  <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n"
                },
                "remoteSocket": {
                    "exists": false,
                    "path": "/run/user/1000/podman/podman.sock"
                },
                "security": {
                    "apparmorEnabled": false,
                    "capabilities": "CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT",
                    "rootless": true,
                    "seccompEnabled": true,
                    "seccompProfilePath": "/usr/share/containers/seccomp.json",
                    "selinuxEnabled": false
                },
                "serviceIsRemote": false,
                "slirp4netns": {
                    "executable": "/usr/bin/slirp4netns",
                    "package": "Unknown",
                    "version": "slirp4netns version 1.2.1\ncommit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194\nlibslirp: 4.7.0\nSLIRP_CONFIG_VERSION_MAX: 4\nlibseccomp: 2.5.5"
                },
                "swapFree": 7451414528,
                "swapTotal": 8191471616,
                "uptime": "11h 21m 46.00s (Approximately 0.46 days)",
                "variant": ""
            },
            "plugins": {
                "authorization": null,
                "log": [
                    "k8s-file",
                    "none",
                    "passthrough",
                    "journald"
                ],
                "network": [
                    "bridge",
                    "macvlan",
                    "ipvlan"
                ],
                "volume": [
                    "local"
                ]
            },
            "registries": {},
            "store": {
                "configFile": "/home/aman/.config/containers/storage.conf",
                "containerStore": {
                    "number": 4,
                    "paused": 0,
                    "running": 0,
                    "stopped": 4
                },
                "graphDriverName": "overlay",
                "graphOptions": {},
                "graphRoot": "/home/aman/.local/share/containers/storage",
                "graphRootAllocated": 343170449408,
                "graphRootUsed": 72350326784,
                "graphStatus": {
                    "Backing Filesystem": "extfs",
                    "Native Overlay Diff": "true",
                    "Supports d_type": "true",
                    "Supports shifting": "false",
                    "Supports volatile": "true",
                    "Using metacopy": "false"
                },
                "imageCopyTmpDir": "/var/tmp",
                "imageStore": {
                    "number": 4
                },
                "runRoot": "/run/user/1000/containers",
                "transientStore": false,
                "volumePath": "/home/aman/.local/share/containers/storage/volumes"
            },
            "version": {
                "APIVersion": "4.9.3",
                "Built": 0,
                "BuiltTime": "Thu Jan  1 05:30:00 1970",
                "GitCommit": "",
                "GoVersion": "go1.22.2",
                "Os": "linux",
                "OsArch": "linux/amd64",
                "Version": "4.9.3"
            }
        },
        "Name": "podman"
    },
    "Image": "quay.io/ramalama/ramalama:0.18",
    "RagImage": "quay.io/ramalama/ramalama-rag:0.18",
    "Runtimes": {
        "Available": [
            "llama.cpp",
            "mlx",
            "vllm"
        ],
        "Default": "llama.cpp"
    },
    "Selinux": false,
    "Shortnames": {
        "Files": [
            "/home/aman/OpenSource/outreachy/testing/ramalama-testing/share/ramalama/shortnames.conf"
        ],
        "Names": {
            "cerebrum": "huggingface://froggeric/Cerebrum-1.0-7b-GGUF/Cerebrum-1.0-7b-Q4_KS.gguf",
            "deepseek": "ollama://deepseek-r1",
            "dragon": "huggingface://llmware/dragon-mistral-7b-v0/dragon-mistral-7b-q4_k_m.gguf",
            "gemma3": "hf://ggml-org/gemma-3-4b-it-GGUF",
            "gemma3:12b": "hf://ggml-org/gemma-3-12b-it-GGUF",
            "gemma3:1b": "hf://ggml-org/gemma-3-1b-it-GGUF/gemma-3-1b-it-Q4_K_M.gguf",
            "gemma3:27b": "hf://ggml-org/gemma-3-27b-it-GGUF",
            "gemma3:4b": "hf://ggml-org/gemma-3-4b-it-GGUF",
            "gemma3n": "hf://ggml-org/gemma-3n-E4B-it-GGUF/gemma-3n-E4B-it-Q8_0.gguf",
            "gemma3n:e2b": "hf://ggml-org/gemma-3n-E2B-it-GGUF/gemma-3n-E2B-it-Q8_0.gguf",
            "gemma3n:e2b-it-f16": "hf://ggml-org/gemma-3n-E2B-it-GGUF/gemma-3n-E2B-it-f16.gguf",
            "gemma3n:e2b-it-q8_0": "hf://ggml-org/gemma-3n-E2B-it-GGUF/gemma-3n-E2B-it-Q8_0.gguf",
            "gemma3n:e4b": "hf://ggml-org/gemma-3n-E4B-it-GGUF/gemma-3n-E4B-it-Q8_0.gguf",
            "gemma3n:e4b-it-f16": "hf://ggml-org/gemma-3n-E4B-it-GGUF/gemma-3n-E4B-it-f16.gguf",
            "gemma3n:e4b-it-q8_0": "hf://ggml-org/gemma-3n-E4B-it-GGUF/gemma-3n-E4B-it-Q8_0.gguf",
            "gpt-5.1": "openai://gpt-5.1-2025-11-13",
            "gpt-oss": "hf://ggml-org/gpt-oss-20b-GGUF",
            "gpt-oss:120b": "hf://ggml-org/gpt-oss-120b-GGUF",
            "gpt-oss:20b": "hf://ggml-org/gpt-oss-20b-GGUF",
            "granite": "ollama://granite3.1-dense",
            "granite-be-3.0:1b": "hf://taronaeo/Granite-3.0-1B-A400M-Instruct-BE-GGUF/granite-3.0-1b-a400m-instruct-be.Q2_K.gguf",
            "granite-be-3.3:2b": "hf://taronaeo/Granite-3.3-2B-Instruct-BE-GGUF/granite-3.3-2b-instruct-be.Q4_K_M.gguf",
            "granite-lab-7b": "huggingface://instructlab/granite-7b-lab-GGUF/granite-7b-lab-Q4_K_M.gguf",
            "granite-lab-8b": "huggingface://ibm-granite/granite-3.3-8b-instruct-GGUF/granite-3.3-8b-instruct-Q4_K_M.gguf",
            "granite-lab:7b": "huggingface://instructlab/granite-7b-lab-GGUF/granite-7b-lab-Q4_K_M.gguf",
            "granite:2b": "ollama://granite3.1-dense:2b",
            "granite:7b": "huggingface://instructlab/granite-7b-lab-GGUF/granite-7b-lab-Q4_K_M.gguf",
            "granite:8b": "ollama://granite3.1-dense:8b",
            "hermes": "huggingface://NousResearch/Hermes-2-Pro-Mistral-7B-GGUF/Hermes-2-Pro-Mistral-7B.Q4_K_M.gguf",
            "ibm/granite": "ollama://granite3.1-dense:8b",
            "ibm/granite:2b": "ollama://granite3.1-dense:2b",
            "ibm/granite:7b": "huggingface://instructlab/granite-7b-lab-GGUF/granite-7b-lab-Q4_K_M.gguf",
            "ibm/granite:8b": "ollama://granite3.1-dense:8b",
            "merlinite": "huggingface://instructlab/merlinite-7b-lab-GGUF/merlinite-7b-lab-Q4_K_M.gguf",
            "merlinite-lab-7b": "huggingface://instructlab/merlinite-7b-lab-GGUF/merlinite-7b-lab-Q4_K_M.gguf",
            "merlinite-lab:7b": "huggingface://instructlab/merlinite-7b-lab-GGUF/merlinite-7b-lab-Q4_K_M.gguf",
            "merlinite:7b": "huggingface://instructlab/merlinite-7b-lab-GGUF/merlinite-7b-lab-Q4_K_M.gguf",
            "mistral": "hf://lmstudio-community/Mistral-7B-Instruct-v0.3-GGUF/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
            "mistral-small3.1": "hf://bartowski/mistralai_Mistral-Small-3.1-24B-Instruct-2503-GGUF/mistralai_Mistral-Small-3.1-24B-Instruct-2503-IQ2_M.gguf",
            "mistral-small3.1:24b": "hf://bartowski/mistralai_Mistral-Small-3.1-24B-Instruct-2503-GGUF/mistralai_Mistral-Small-3.1-24B-Instruct-2503-IQ2_M.gguf",
            "mistral:7b": "hf://lmstudio-community/Mistral-7B-Instruct-v0.3-GGUF/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
            "mistral:7b-v1": "huggingface://TheBloke/Mistral-7B-Instruct-v0.1-GGUF/mistral-7b-instruct-v0.1.Q5_K_M.gguf",
            "mistral:7b-v2": "huggingface://TheBloke/Mistral-7B-Instruct-v0.2-GGUF/mistral-7b-instruct-v0.2.Q4_K_M.gguf",
            "mistral:7b-v3": "hf://lmstudio-community/Mistral-7B-Instruct-v0.3-GGUF/Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
            "mistral_code_16k": "huggingface://TheBloke/Mistral-7B-Code-16K-qlora-GGUF/mistral-7b-code-16k-qlora.Q4_K_M.gguf",
            "mistral_codealpaca": "huggingface://TheBloke/Mistral-7B-codealpaca-lora-GGUF/mistral-7b-codealpaca-lora.Q4_K_M.gguf",
            "mixtao": "huggingface://MaziyarPanahi/MixTAO-7Bx2-MoE-Instruct-v7.0-GGUF/MixTAO-7Bx2-MoE-Instruct-v7.0.Q4_K_M.gguf",
            "openchat": "huggingface://TheBloke/openchat-3.5-0106-GGUF/openchat-3.5-0106.Q4_K_M.gguf",
            "openorca": "huggingface://TheBloke/Mistral-7B-OpenOrca-GGUF/mistral-7b-openorca.Q4_K_M.gguf",
            "phi2": "huggingface://MaziyarPanahi/phi-2-GGUF/phi-2.Q4_K_M.gguf",
            "qwen2.5vl": "hf://ggml-org/Qwen2.5-VL-32B-Instruct-GGUF",
            "qwen2.5vl:2b": "hf://ggml-org/Qwen2.5-VL-2B-Instruct-GGUF",
            "qwen2.5vl:32b": "hf://ggml-org/Qwen2.5-VL-32B-Instruct-GGUF",
            "qwen2.5vl:3b": "hf://ggml-org/Qwen2.5-VL-3B-Instruct-GGUF",
            "qwen2.5vl:7b": "hf://ggml-org/Qwen2.5-VL-7B-Instruct-GGUF",
            "smollm:135m": "hf://HuggingFaceTB/smollm-135M-instruct-v0.2-Q8_0-GGUF",
            "smolvlm": "hf://ggml-org/SmolVLM-500M-Instruct-GGUF",
            "smolvlm:256m": "hf://ggml-org/SmolVLM-256M-Instruct-GGUF",
            "smolvlm:2b": "hf://ggml-org/SmolVLM-Instruct-GGUF",
            "smolvlm:500m": "hf://ggml-org/SmolVLM-500M-Instruct-GGUF",
            "stories-be:260k": "hf://taronaeo/tinyllamas-BE/stories260K-be.gguf",
            "tiny": "hf://TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF",
            "tinyllama": "hf://TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF"
        },
        "Sources": [
            "/home/aman/OpenSource/outreachy/testing/ramalama-testing/share/ramalama/shortnames.conf"
        ]
    },
    "Store": "/home/aman/.local/share/ramalama",
    "UseContainer": true,
    "Version": "0.18.0"
}
```

### Upstream Latest Release

Yes

### Additional environment details

- **OS:** Linux Mint 22.3
- **Python:** 3.12
- **Install method:** pip install ramalama
- **Ramalama version:** 0.18.0
- **Reproduced in fresh venv:** yes

#### Regression check
I tested two versions in the same environment:
- `ramalama==0.17.0`: `ramalama list` works and prints models.
- `ramalama==0.18.0`: `ramalama list` crashes with `AttributeError: 'str' object has no attribute 'timestamp'`.

This appears to be a regression introduced b/w 0.17.0 and 0.18.0.

**Comment by amkr6207** [comment]
@rhatdan, @mikebonnet, @bmahabirbu PTAL. Thanks!

**Comment by amkr6207** [comment]
@rhatdan, @mikebonnet, @bmahabirbu 

I’d like to work on this issue. I’ve confirmed it works on 0.17.0 and fails on 0.18.0, so it appears to be a regression. I can open a PR. 

Thanks!

**Comment by amkr6207** [comment]
@containers/ramalama-maintainers

**Comment by mikebonnet** [comment]
@amkr6207 Assigned
